### Create report
POST http://localhost:3000/reports
content-type: application/json

{
    "make" : "kia",
    "model" : "k7",
    "year" : 2016,
    "mileage" : 8005090,
    "lng" : 41,
    "lat" : 45,
    "price" : 140391778
}



### Approve an existing report
PATCH http://localhost:3000/reports/9
content-type: application/json

{
    "approved" : true
}

### Get estimate for an existing vehicle
GET http://localhost:3000/reports?make=kia&model=k7&lng=40&lat=40&mileage=4005090&year=2015
